### ISSUE TITLE
where is the vs2017.vcproj and vs2017.sln? Can you supply it?

### ISSUE THREAD

**Issue by nneesshh** [frank-lesser/Godot3-Win64-LSW-Build#1]
This work is cool.
Scons use python magic and I am a pure vs project user.
jit for gdscript is a hard work, so I wonder if the luajit can be supported by your work now

**Comment by frank-lesser** [comment]
Thx, I have updated the Readme (https://github.com/frank-lesser/Godot3-Win64-LSW-Build/blob/master/readme.md) & added (https://github.com/frank-lesser/Godot3-Win64-LSW-Build/blob/master/Godot-LSW-extensibility.md)
